### ISSUE TITLE
IntelliJ 2022.2 compatibility

### ISSUE THREAD

**Issue by Kernald** [Toshibane/ComposeIconViewer#1]
As of right now, the plugin is only compatible with IntelliJ 2020.2 -- 2022.1.4. Do you have any timeline for a 2022.2 compatibility?

**Comment by ToshiBaguette** [comment]
After checking, the plugin is already compatible.

I updated the max version of the plugin, see [the last commit](https://github.com/Toshibane/ComposeIconViewer/commit/be7f7c3040e4ad5078e0f69227883bccec28feae).

It should be accepted tomorrow by Jetbrains on the marketplace.
